properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  datadogAgentImage:
    type: string
    default: datadog/agent:latest
    x-google-marketplace:
      type: IMAGE
  apiKey:
    title: Datadog API key
    description: Get your Datadog API key at https://app.datadoghq.com/account/settings#api
    type: string
    maxLength: 32
    pattern: '[a-z0-9]+'

required:
- name
- namespace
- datadogAgentImage
- apiKey
